# render.yaml（フル版：Web / Worker / Cron / Key-Value をまとめて管理）

services:
  # --- Web (FastAPIなど) ---
  - type: web
    name: restaurant-ai-web
    runtime: python
    region: oregon                 # ← あなたのDBと同じリージョンに
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true               # pushで自動デプロイ（運用に合わせて変更可）
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-ai-db    # ← Renderの既存Postgres名
          property: connectionString
      - key: REDIS_URL
        fromService:               # 下に定義する Key-Value の接続URLを流し込む
          name: restaurant-ai-kv
          type: keyvalue
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false

  # --- Worker（非同期ジョブ。まずはダミー起動でOK） ---
  - type: worker
    name: restaurant-ai-worker
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py  # 中身は後述のダミーでOK（先に起動だけ通す）
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-ai-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: restaurant-ai-kv
          type: keyvalue
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false

  # --- Cron（定刻バッチ。JST 06:15 = UTC 21:15の例） ---
  - type: cron
    name: restaurant-ai-daily
    runtime: python
    region: oregon
    schedule: "15 21 * * *"        # UTC指定：毎日 21:15 UTC（= 翌朝 06:15 JST）
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/daily_job.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-ai-db
          property: connectionString

  # --- Key-Value（Redis互換：Celery/RQのbrokerなどに） ---
  - type: keyvalue
    name: restaurant-ai-kv
    ipAllowList: []                 # 内部接続のみ許可（外部から繋がせない）
